# Experiment 14 - Data Normalization and Data Type Conversion

## Name : Krishiv Sharma
## PRN : 25070123065
## Batch : Entc A-3
## Date : 01-04-26

In [1]:
# Dataset

import pandas as pd
import numpy as np

data = {
    'Product' : ['Laptop', 'Mobile', 'Tablet', 'Headphones', 'Smartwatch', 'Camera'],
    'Price' : [75000, 50000, 65000, 10000, 20000, 45000],
    'Units_Sold' : [100, 50, 75, 200, 150, 125],
    'Discount' : [10, 15, 12, 20, 18, 8]
}

df = pd.DataFrame(data)
df

      Product  Price  Units_Sold  Discount
0      Laptop  75000         100        10
1      Mobile  50000          50        15
2      Tablet  65000          75        12
3  Headphones  10000         200        20
4  Smartwatch  20000         150        18
5      Camera  45000         125         8

In [4]:
#1. Min-Max Normalization
# Min-Max normalization for Price

df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())

print("\nMin-Max Normalized Price:")
print(df[['Product', 'Price', 'Price_MinMax']])

Min-Max Normalized Price:
      Product  Price  Price_MinMax
0      Laptop  75000      1.000000
1      Mobile  50000      0.615385
2      Tablet  65000      0.846154
3  Headphones  10000      0.000000
4  Smartwatch  20000      0.153846
5      Camera  45000      0.538462

In [7]:
# Normalize Multiple Columns

cols = ['Price', 'Units_Sold', 'Discount']

df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())

print("\nNormalized Dataset")
print(df_norm)

Normalized Dataset
      Price  Units_Sold  Discount
0  1.000000    0.333333  0.166667
1  0.615385    0.000000  0.583333
2  0.846154    0.166667  0.333333
3  0.000000    1.000000  1.000000
4  0.153846    0.666667  0.833333
5  0.538462    0.500000  0.000000

In [10]:
#2. Z-score Normalization

df['Units_Zscore'] = (df['Units_Sold'] - df['Units_Sold'].mean()) / df['Units_Sold'].std()

print("\nZ-score Normalized Units_Sold:")
print(df[['Product', 'Units_Sold', 'Units_Zscore']])

Z-score Normalized Units_Sold:
      Product  Units_Sold  Units_Zscore
0      Laptop         100     -0.308607
1      Mobile          50     -1.234427
2      Tablet          75     -0.771517
3  Headphones         200      1.543033
4  Smartwatch         150      0.617213
5      Camera         125      0.154303

In [11]:
#3. Decimal Scaling
df['Price_Decimal'] = df['Price'] / 100000

print("\nDecimal Scaled Price:")
print(df[['Product', 'Price', 'Price_Decimal']])

Decimal Scaled Price:
      Product  Price  Price_Decimal
0      Laptop  75000           0.75
1      Mobile  50000           0.50
2      Tablet  65000           0.65
3  Headphones  10000           0.10
4  Smartwatch  20000           0.20
5      Camera  45000           0.45

# Part-B : Turning Categorical variables into quantitative variables in Python

In [12]:
data = {
    'Order_ID' : [101, 102, 103, 104, 105, 106],
    'Customer_Gender' : ['Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
    'Payment_Method' : ['Credit Card', 'PayPal', 'Cash', 'Credit Card', 'PayPal', 'Cash'],
    'Product_Category' : ['Electronics', 'Clothing', 'Electronics', 'Clothing', 'Electronics', 'Clothing'],
    'City' : ['New York', 'Los Angeles', 'Chicago', 'San Francisco', 'Seattle', 'Boston'],
    'Order_Value' : [1500, 800, 2000, 1200, 1800, 900],
}

df = pd.DataFrame(data)
df

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value
0,101,Male,Credit Card,Electronics,New York,1500
1,102,Female,PayPal,Clothing,Los Angeles,800
2,103,Male,Cash,Electronics,Chicago,2000
3,104,Female,Credit Card,Clothing,San Francisco,1200
4,105,Male,PayPal,Electronics,Seattle,1800
5,106,Female,Cash,Clothing,Boston,900

In [14]:
#Method 1: Label Encoding

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Gender_Label'] = le.fit_transform(df['Customer_Gender'])

print(df)

   Order_ID Customer_Gender Payment_Method Product_Category           City  \
0       101            Male    Credit Card      Electronics       New York
1       102          Female         PayPal         Clothing    Los Angeles
2       103            Male           Cash      Electronics        Chicago
3       104          Female    Credit Card         Clothing  San Francisco
4       105            Male         PayPal      Electronics        Seattle
5       106          Female           Cash         Clothing         Boston

   Order_Value  Gender_Label
0         1500             1
1          800             0
2         2000             1
3         1200             0
4         1800             1
5          900             0

In [15]:
#Method 2: One-Hot Encoding

df_encoded = pd.get_dummies(df, columns=['Payment_Method'])

print(df_encoded)

   Order_ID Customer_Gender Product_Category           City  Order_Value  \
0       101            Male      Electronics       New York         1500
1       102          Female         Clothing    Los Angeles          800
2       103            Male      Electronics        Chicago         2000
3       104          Female         Clothing  San Francisco         1200
4       105            Male      Electronics        Seattle         1800
5       106          Female         Clothing         Boston          900

   Gender_Label  Payment_Method_Cash  Payment_Method_Credit Card  \
0             1                False                        True
1             0                False                       False
2             1                 True                       False
3             0                False                        True
4             1                False                       False
5             0                 True                       False

   Payment_Method_PayPal
0                  False
1                   True
2                  False
3                  False
4                   True
5                  False

In [16]:
#Method 3: Dummy Encoding (Drop First)

df_dummy = pd.get_dummies(df, columns=['Payment_Method'], drop_first=True)

print(df_dummy)

   Order_ID Customer_Gender Product_Category           City  Order_Value  \
0       101            Male      Electronics       New York         1500
1       102          Female         Clothing    Los Angeles          800
2       103            Male      Electronics        Chicago         2000
3       104          Female         Clothing  San Francisco         1200
4       105            Male      Electronics        Seattle         1800
5       106          Female         Clothing         Boston          900

   Gender_Label  Payment_Method_Credit Card  Payment_Method_PayPal
0             1                        True                  False
1             0                       False                   True
2             1                       False                  False
3             0                        True                  False
4             1                       False                   True
5             0                       False                  False

# New Dataset Operations

In [19]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/amazon_products_dataset_Expt-14 (1).csv')

In [22]:
#Min-Max Normalization

df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())

print("\nMin-Max Normalized Price:")
print(df[['Product_Name', 'Price', 'Price_MinMax']])

Min-Max Normalized Price:
                   Product_Name  Price  Price_MinMax
0                Wireless Mouse    799      0.020243
1             Bluetooth Speaker   1499      0.048583
2                  USB Keyboard    699      0.016194
3                Gaming Headset   2499      0.089069
4                    Smartwatch   3999      0.149798
5                    Power Bank   1199      0.036437
6                  Laptop Stand    899      0.024291
7                        Webcam   1899      0.064777
8                  Portable SSD   5499      0.210526
9              Wireless Charger    999      0.028340
10  Noise Cancelling Headphones   7999      0.311741
11          Mechanical Keyboard   4599      0.174089
12                 Gaming Mouse   1599      0.052632
13                 Tablet Stand    699      0.016194
14                      USB Hub    899      0.024291
15          External Hard Drive   6499      0.251012
16            Smartphone Tripod   1199      0.036437
17              Laptop Backpack   1999      0.068826
18            Bluetooth Earbuds   2999      0.109312
19                LED Desk Lamp   1299      0.040486
20                 Phone Holder    499      0.008097
21            Wireless Keyboard   2499      0.089069
22             Portable Monitor   8999      0.352227
23                   Smart Plug    799      0.020243
24                  WiFi Router   3499      0.129555
25              Graphics Tablet   4599      0.174089
26                   VR Headset  12999      0.514170
27                   Microphone   2199      0.076923
28             Smart Light Bulb    699      0.016194
29           Laptop Cooling Pad   1499      0.048583
30                Action Camera   9999      0.392713
31               Smart Doorbell   5999      0.230769
32              Streaming Stick   3499      0.129555
33           Portable Projector  11999      0.473684
34                 Gaming Chair  15999      0.635628
35               Desk Organizer    599      0.012146
36              USB Flash Drive    799      0.020243
37       Phone Screen Protector    299      0.000000
38                Laptop Sleeve    999      0.028340
39           Wireless Presenter   1499      0.048583
40         Tablet Keyboard Case   2999      0.109312
41             Smart Thermostat  10999      0.433198
42              Security Camera   4999      0.190283
43                 Drone Camera  24999      1.000000
44              Electric Kettle   1999      0.068826
45                    Air Fryer   7999      0.311741
46                 Robot Vacuum  18999      0.757085
47                  Smart Scale   2499      0.089069
48          Digital Photo Frame   3499      0.129555
49                 Portable Fan    999      0.028340

In [24]:
#Z-Score Normalization

df['Units_Zscore'] = (df['Units_Sold'] - df['Units_Sold'].mean()) / df['Units_Sold'].std()

print("\nZ-score Normalized Units_Sold:")
print(df[['Product_Name', 'Units_Sold', 'Units_Zscore']])

Z-score Normalized Units_Sold:
                   Product_Name  Units_Sold  Units_Zscore
0                Wireless Mouse         350      0.812282
1             Bluetooth Speaker         220     -0.260855
2                  USB Keyboard         180     -0.591051
3                Gaming Headset         410      1.307576
4                    Smartwatch         520      2.215615
5                    Power Bank         390      1.142478
6                  Laptop Stand         140     -0.921247
7                        Webcam         260      0.069341
8                  Portable SSD         330      0.647184
9              Wireless Charger         190     -0.508502
10  Noise Cancelling Headphones         610      2.958556
11          Mechanical Keyboard         290      0.316988
12                 Gaming Mouse         340      0.729733
13                 Tablet Stand         120     -1.086345
14                      USB Hub         200     -0.425953
15          External Hard Drive         310      0.482086
16            Smartphone Tripod         210     -0.343404
17              Laptop Backpack         420      1.390125
18            Bluetooth Earbuds         530      2.298164
19                LED Desk Lamp         260      0.069341
20                 Phone Holder         150     -0.838698
21            Wireless Keyboard         310      0.482086
22             Portable Monitor         170     -0.673600
23                   Smart Plug         210     -0.343404
24                  WiFi Router         390      1.142478
25              Graphics Tablet         160     -0.756149
26                   VR Headset         140     -0.921247
27                   Microphone         270      0.151890
28             Smart Light Bulb         240     -0.095757
29           Laptop Cooling Pad         260      0.069341
30                Action Camera         200     -0.425953
31               Smart Doorbell         180     -0.591051
32              Streaming Stick         430      1.472674
33           Portable Projector         120     -1.086345
34                 Gaming Chair          90     -1.333992
35               Desk Organizer         160     -0.756149
36              USB Flash Drive         320      0.564635
37       Phone Screen Protector         380      1.059929
38                Laptop Sleeve         210     -0.343404
39           Wireless Presenter         130     -1.003796
40         Tablet Keyboard Case         150     -0.838698
41             Smart Thermostat         110     -1.168894
42              Security Camera         260      0.069341
43                 Drone Camera          70     -1.499090
44              Electric Kettle         310      0.482086
45                    Air Fryer         200     -0.425953
46                 Robot Vacuum         120     -1.086345
47                  Smart Scale         170     -0.673600
48          Digital Photo Frame         150     -0.838698
49                 Portable Fan         240     -0.095757

In [26]:
# Decimal Scaling

df['Price_Decimal'] = df['Price'] / 100000

print("\nDecimal Scaled Price:")
print(df[['Product_Name', 'Price', 'Price_Decimal']])

Decimal Scaled Price:
                   Product_Name  Price  Price_Decimal
0                Wireless Mouse    799        0.00799
1             Bluetooth Speaker   1499        0.01499
2                  USB Keyboard    699        0.00699
3                Gaming Headset   2499        0.02499
4                    Smartwatch   3999        0.03999
5                    Power Bank   1199        0.01199
6                  Laptop Stand    899        0.00899
7                        Webcam   1899        0.01899
8                  Portable SSD   5499        0.05499
9              Wireless Charger    999        0.00999
10  Noise Cancelling Headphones   7999        0.07999
11          Mechanical Keyboard   4599        0.04599
12                 Gaming Mouse   1599        0.01599
13                 Tablet Stand    699        0.00699
14                      USB Hub    899        0.00899
15          External Hard Drive   6499        0.06499
16            Smartphone Tripod   1199        0.01199
17              Laptop Backpack   1999        0.01999
18            Bluetooth Earbuds   2999        0.02999
19                LED Desk Lamp   1299        0.01299
20                 Phone Holder    499        0.00499
21            Wireless Keyboard   2499        0.02499
22             Portable Monitor   8999        0.08999
23                   Smart Plug    799        0.00799
24                  WiFi Router   3499        0.03499
25              Graphics Tablet   4599        0.04599
26                   VR Headset  12999        0.12999
27                   Microphone   2199        0.02199
28             Smart Light Bulb    699        0.00699
29           Laptop Cooling Pad   1499        0.01499
30                Action Camera   9999        0.09999
31               Smart Doorbell   5999        0.05999
32              Streaming Stick   3499        0.03499
33           Portable Projector  11999        0.11999
34                 Gaming Chair  15999        0.15999
35               Desk Organizer    599        0.00599
36              USB Flash Drive    799        0.00799
37       Phone Screen Protector    299        0.00299
38                Laptop Sleeve    999        0.00999
39           Wireless Presenter   1499        0.01499
40         Tablet Keyboard Case   2999        0.02999
41             Smart Thermostat  10999        0.10999
42              Security Camera   4999        0.04999
43                 Drone Camera  24999        0.24999
44              Electric Kettle   1999        0.01999
45                    Air Fryer   7999        0.07999
46                 Robot Vacuum  18999        0.18999
47                  Smart Scale   2499        0.02499
48          Digital Photo Frame   3499        0.03499
49                 Portable Fan    999        0.00999

In [32]:
# Turning Categorical variables into quantitative variables

df = pd.read_csv('/Student-Dataset.csv')

In [33]:
# Label Encoding - Placement Status

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Placement_Label'] = le.fit_transform(df['Placement_Status'])

print(df)

   Roll_No  Gender  Department  CGPA  Number_of_Backlogs  \
0      101  Female    Computer   8.2                   0
1      102    Male          IT   7.5                   1
2      103  Female        ENTC   9.1                   0
3      104    Male  Mechanical   6.8                   2
4      105  Female    Computer   8.7                   0
5      106    Male       Civil   7.2                   3
6      107  Female          IT   8.9                   0
7      108    Male    Computer   6.5                   1
8      109  Female        ENTC   7.8                   0
9      110    Male  Mechanical   7.0                   2

   Attendance_Percentage Placement_Status  Salary  Placement_Label
0                     92           Placed  450000                1
1                     85       Not Placed       0                0
2                     96           Placed  550000                1
3                     78       Not Placed       0                0
4                     88           Placed  480000                1
5                     72       Not Placed       0                0
6                     91           Placed  500000                1
7                     80       Not Placed       0                0
8                     84           Placed  420000                1
9                     76       Not Placed       0                0

In [34]:
# One-Hot Encoding - Department

df_encoded = pd.get_dummies(df, columns=['Department'])

print(df_encoded)

   Roll_No  Gender  CGPA  Number_of_Backlogs  Attendance_Percentage  \
0      101  Female   8.2                   0                     92
1      102    Male   7.5                   1                     85
2      103  Female   9.1                   0                     96
3      104    Male   6.8                   2                     78
4      105  Female   8.7                   0                     88
5      106    Male   7.2                   3                     72
6      107  Female   8.9                   0                     91
7      108    Male   6.5                   1                     80
8      109  Female   7.8                   0                     84
9      110    Male   7.0                   2                     76

  Placement_Status  Salary  Placement_Label  Department_Civil  \
0           Placed  450000                1             False
1       Not Placed       0                0             False
2           Placed  550000                1             False
3       Not Placed       0                0             False
4           Placed  480000                1             False
5       Not Placed       0                0              True
6           Placed  500000                1             False
7       Not Placed       0                0             False
8           Placed  420000                1             False
9       Not Placed       0                0             False

   Department_Computer  Department_ENTC  Department_IT  Department_Mechanical
0                 True            False          False                  False
1                False            False           True                  False
2                False             True          False                  False
3                False            False          False                   True
4                 True            False          False                  False
5                False            False          False                  False
6                False            False           True                  False
7                 True            False          False                  False
8                False             True          False                  False
9                False            False          False                   True

In [35]:
# Dummies - Department

df_dummy = pd.get_dummies(df, columns=['Department'], drop_first=True)

print(df_dummy)

   Roll_No  Gender  CGPA  Number_of_Backlogs  Attendance_Percentage  \
0      101  Female   8.2                   0                     92
1      102    Male   7.5                   1                     85
2      103  Female   9.1                   0                     96
3      104    Male   6.8                   2                     78
4      105  Female   8.7                   0                     88
5      106    Male   7.2                   3                     72
6      107  Female   8.9                   0                     91
7      108    Male   6.5                   1                     80
8      109  Female   7.8                   0                     84
9      110    Male   7.0                   2                     76

  Placement_Status  Salary  Placement_Label  Department_Computer  \
0           Placed  450000                1                 True
1       Not Placed       0                0                False
2           Placed  550000                1                False
3       Not Placed       0                0                False
4           Placed  480000                1                 True
5       Not Placed       0                0                False
6           Placed  500000                1                False
7       Not Placed       0                0                 True
8           Placed  420000                1                False
9       Not Placed       0                0                False

   Department_ENTC  Department_IT  Department_Mechanical
0            False          False                  False
1            False           True                  False
2             True          False                  False
3            False          False                   True
4            False          False                  False
5            False          False                  False
6            False           True                  False
7            False          False                  False
8             True          False                  False
9            False          False                   True